version: '3'
services:
  flask:
    build: ./test-app
    container_name: flask
    env_file: .env
    depends_on:
      - blazegraph              
    restart: on-failure
    volumes:
      - ./test-app:/backend
    ports:
      - "${PORT}:${PORT}"
  blazegraph:
    build: ./blazegraph
    container_name: blazegraph
    restart: on-failure
    ports:
      - "9999:9999"
networks:
  defaults: